# Generated by Django 3.2.5 on 2021-09-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstour',
            name='image',
            field=models.ImageField(null=True, upload_to='static/newstour/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
