# Generated by Django 3.2.5 on 2021-10-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_auto_20211005_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='totlePrice',
            new_name='totalPrice',
        ),
    ]
